eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: orders
          uri: http://localhost:8092
          predicates:
            - Path=/api/v1/orders/**
        - id: kitchens
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/kitchens/**    
        - id: courtiers
          uri: http://localhost:8091
          predicates:
            - Path=/api/v1/courtiers/**    
        - id: restaurants
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/restaurants/**  
management:
  tracing:
    sampling:
      probability: 1.0
